### ISSUE TITLE
Implement TreeObject class Methods 

### ISSUE THREAD

**Issue by JacobSwierstra** [ConnorEspino/CS321-003-f21-team-09#34]
References user story #13

Implements all of the TreeObject methods

**Comment by ConnorEspino** [comment]
Might need an equals() method to compare two TreeObjects, but other than that I think it's ready to close.

**Comment by ConnorEspino** [comment]
I don't think we need to overwrite the hashcode method and I'm pretty sure the equals method should be comparing the keys directly rather than the hashcode of the keys.

**Comment by ConnorEspino** [comment]
Reopened to add frequency overloaded constructor for when reading and creating from a binary file.
